In [ ]:
import numpy as np
import random as rnd

from numpy.random.mtrand import permutation
import itertools
import time

In [ ]:
symbol_size = 34 

string_input = "ЛещунАнна"

rus_symbol_list = ''.join([chr(i) for i in range(ord('а'), ord('а') + 6)] + [chr(ord('а') + 33)] + [chr(i) for i in range(ord('а') + 6, ord('а') + 32)])

In [ ]:
def create_symbol_index(string_input):
  symbol_list = list(string_input.lower())

  index_matrix = []
  for i in range(len(symbol_list)):
    for j in range(len(rus_symbol_list)):
      if(symbol_list[i] == rus_symbol_list[j]):
        index_matrix.append(j + 1)
  return index_matrix

In [ ]:
def create_matrix_byFIO(string_input, size):
  index, index_matrix = 0, create_symbol_index(string_input)
  result_matrix_FIO = np.zeros((size, size))
  np.fill_diagonal(result_matrix_FIO, symbol_size)

  for i in range(size):
    for j in range(size):
      if(j <= i - 1):
        if(index < len(index_matrix)):
          result_matrix_FIO[i, j] = index_matrix[index]
          result_matrix_FIO[j, i] = result_matrix_FIO[i, j]
          index += 1
        elif(index > len(index_matrix)):
          break
        else:
          result_matrix_FIO[i, j], result_matrix_FIO[j, i] = 1, 1

  print('Начальная матрица:')
  print(result_matrix_FIO)
  return result_matrix_FIO

In [ ]:
def create_matrix_random(size):
  result_matrix_random = np.zeros((size, size))
  np.fill_diagonal(result_matrix_random, symbol_size)

  for i in range(size):
    for j in range(size):
      if(j <= i - 1):
        result_matrix_random[i, j] = rnd.randint(1, 33)
        result_matrix_random[j, i] = result_matrix_random[i, j]

  print('Начальная матрица(random): ')
  print(result_matrix_random)
  return result_matrix_random

In [ ]:
#Функция нахождения минимального значения в строке и его позиции/ый
def get_min_value(matrix, index):
  min_value = np.min(matrix[index, :])
  positions = [ind for ind, val in enumerate(matrix[index, :]) if val == min_value]
  return min_value, positions

In [ ]:
#Функция замены числа на что-то большое
def replace_value(matrix, index):
  matrix[:, index] = 34
  return matrix

Жадный алгоритм

In [ ]:
#Функция расчета жадного алгоритма
def greedy_algorithm(matrix_FIO):
  i = 0
  first = matrix_FIO[:, 0].copy()
  list_min_value = []
  position = 0
  list_positions = []
  list_positions.append(1)
  while(i < len(matrix_FIO)):
    if(i == len(matrix_FIO) - 1):
      for i in range(len(matrix_FIO[:, 0])):
        matrix_FIO[i, 0] = first[i]

    min_value, positions = get_min_value(matrix_FIO, position)
    list_min_value.append(min_value)
    matrix_FIO = replace_value(matrix_FIO, position)
    if(len(positions) >= 1):
      position = positions[0]
    else:
      position = positions[0] 
    list_positions.append(position + 1) 
    #print(matrix_FIO)
    i = i + 1

  print(f'Позиции: {list_positions}')
  print(f'Минимумы: {list_min_value}')
  print(f'Сумма: {np.sum(list_min_value)} мин\n')

In [ ]:
matrix_FIO_5_1 = create_matrix_byFIO(string_input, 5)
matrix_FIO_5_2 = matrix_FIO_5_1.copy()

matrix_random_10_1 = create_matrix_random(10)
matrix_random_10_2 = matrix_random_10_1.copy()

Начальная матрица:
[[34. 13.  6. 21. 15.]
 [13. 34. 27. 15. 15.]
 [ 6. 27. 34.  1.  1.]
 [21. 15.  1. 34.  1.]
 [15. 15.  1.  1. 34.]]
Начальная матрица(random): 
[[34. 17. 29. 29. 13. 18. 29. 28. 29. 33.]
 [17. 34. 30. 10. 11. 25. 30. 20. 18. 26.]
 [29. 30. 34. 25. 18. 19. 16.  7. 29.  9.]
 [29. 10. 25. 34. 13. 25. 19.  3.  1. 32.]
 [13. 11. 18. 13. 34. 10. 20. 15. 20. 31.]
 [18. 25. 19. 25. 10. 34. 21. 33. 20. 22.]
 [29. 30. 16. 19. 20. 21. 34. 17. 31. 16.]
 [28. 20.  7.  3. 15. 33. 17. 34. 27. 20.]
 [29. 18. 29.  1. 20. 20. 31. 27. 34. 15.]
 [33. 26.  9. 32. 31. 22. 16. 20. 15. 34.]]


In [ ]:
print('Матрица 5х5: ')
greedy_algorithm(matrix_FIO_5_1)

print('Матрица 10х10: ')
greedy_algorithm(matrix_random_10_1)

Матрица 5х5: 
Позиции: [1, 3, 4, 5, 2, 1]
Минимумы: [6.0, 1.0, 1.0, 15.0, 13.0]
Сумма: 36.0 мин

Матрица 10х10: 
Позиции: [1, 5, 6, 3, 8, 4, 9, 10, 7, 2, 1]
Минимумы: [13.0, 10.0, 19.0, 7.0, 3.0, 1.0, 15.0, 16.0, 30.0, 17.0]
Сумма: 131.0 мин



Полный перебор

In [ ]:
def full_search(input_matrix):
  sum_list = []
  row_value = []
  for row in itertools.permutations(range(len(input_matrix[0, :]))):
    sum = 0
    for i in range(len(row)):
      sum += input_matrix[i][row[i]]
    sum_list.append(sum)

    l = list(row)
    l.append(l[0])
    for i in range(len(l)):
      l[i] += 1
    row_value.append(l)

  print(f'Последовательность: {row_value[np.argmin(sum_list)]}')
  print(f'Мин. значение: {min(sum_list)} мин')
  print(f'Макс. значение: {max(sum_list)} мин')
  

In [ ]:
print('Матрица 5х5: ')
full_search(matrix_FIO_5_2)

print('\nМатрица 10x10: ')
full_search(matrix_random_10_2)

Матрица 5х5: 
Последовательность: [2, 1, 4, 5, 3, 2]
Мин. значение: 29.0 мин
Макс. значение: 170.0 мин

Матрица 10x10: 
Последовательность: [2, 1, 8, 9, 6, 5, 10, 3, 4, 7, 2]
Мин. значение: 102.0 мин
Макс. значение: 340.0 мин
